### ISSUE TITLE
Rename configuration field

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Struggleton/TitleScreenBGM#2]
Assuming (#1) gets resolved at some point, it may be worth renaming the `bgm_hash` field in the configuration to `ui_bgm_id`. This may improve a user's understanding between the game's official key names and what data this plugin expects.

**Comment by Struggleton** [comment]
Good idea! Dunno why I didn't use the game's field name initially. Better early than later; renamed the field in commit e6c59a2e5c80492fba08e3c9ff41d6a258e9017a and updated new usage readme in commit 9330bb8617e270c1bd7146b20ceec3be8a4f0b52.
