### ISSUE TITLE
Eliminate unsafe code

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Struggleton/TitleScreenBGM#3]
Due to the use of a mutable static variable for the BGM playing flag, this requires reads and writes to be wrapped in `unsafe` blocks as a result of Rust trying to avoid bugs from concurrency.

One solution would be to switch out the type of variable with an [AtomicBool](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicBool.html#). This type is thread-safe and does not require the use of `unsafe` blocks.

Since your offset variables are not being mutated at all, you can remove the `mut` modifier from them. Additionally, you may want to consider changing them to constants so they don't have a reserved place in the binary and are inlined into the code instead.

**Comment by Struggleton** [comment]
Thanks - fixed in 10781d5dbb6228c43523da413fab1cac39f875af and e93af12ab0e05282e33798197a7abbe03f62a4e4!
