### ISSUE TITLE
Run cargo fmt

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Struggleton/TitleScreenBGM#4]
This is more of a nitpick than an actual issue with the code, but there are a couple places where indentation is improper or inconsistent (namely [here](https://github.com/Struggleton/TitleScreenBGM/blob/v1.0/src/lib.rs#L61) and [here](https://github.com/Struggleton/TitleScreenBGM/blob/v1.0/src/config.rs#L42)), potentially making it a bit more difficult for a third-party reader to understand the code. Running [rustfmt](https://github.com/rust-lang/rustfmt?tab=readme-ov-file) on the project will format the code to meet a standard defined by the Rust community. Some changes will include converting tabs to spaces, ensuring proper levels of indentation, and moving some code to new lines if deemed too long. Settings can be configured if you're not happy with the defaults.

**Comment by Struggleton** [comment]
Thanks! I wasn't aware of that component - that's really useful. Fixed in commit 7214d24b1d3e0f3a72ccf7ee6a1a40f4b9eb6679
