### ISSUE TITLE
Avoid unnecessary fallible conversion from string to Hash40

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Struggleton/TitleScreenBGM#5]
Certain variables ([here](https://github.com/Struggleton/TitleScreenBGM/blob/v2.0/src/lib.rs#L41) and [here](https://github.com/Struggleton/TitleScreenBGM/blob/v2.0/src/config.rs#L16)) are using a fallible conversion method to `Hash40` when passing in string literals. If you know the input is valid and have an infallible conversion method available to you, it is preferred to use that instead to avoid unnecessary handling of potential errors. The conversion method in question is [`Hash40::new`](https://docs.rs/hash40/latest/hash40/struct.Hash40.html#method.new).

**Comment by Struggleton** [comment]
Fixed in commit 7d807a5e149ca6b8cb4daed797226c1d41bd404d
