### ISSUE TITLE
Use a more logical and valid ui_bgm_id value for playing silent audio

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Struggleton/TitleScreenBGM#6]
Currently, the hash label used to play silent audio is `m21b_gaw_gamer_mom`. However, this seems like an arbitrary choice and is potentially an invalid one at that, as `the_csk_collection_api::play_bgm` should expect a `ui_bgm_id` hash and not a `data_name` hash. A better choice of an argument would be `ui_bgm_crs2_49_commonsilent_lp`.

**Comment by Struggleton** [comment]
Didn't know that one existed - good idea! Updated in commit a75e89420aa4ed18a2e08e805004d43783c12edc
